[build]
  base    = "WolfTasksServer/my-angular-app"
  command = "npm install --include=dev && npm run build"
  publish = "dist/my-angular-app/browser"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
